# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rService.proto\" \n\x08Resource\x12\x14\n\x0cresourceName\x18\x02 \x01(\t\"<\n\x13TransactionResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x10\n\x08Response\x18\x02 \x01(\t2B\n\x0eProductService\x12\x30\n\x0bgetResource\x12\t.Resource\x1a\x14.TransactionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESOURCE']._serialized_start=17
  _globals['_RESOURCE']._serialized_end=49
  _globals['_TRANSACTIONRESPONSE']._serialized_start=51
  _globals['_TRANSACTIONRESPONSE']._serialized_end=111
  _globals['_PRODUCTSERVICE']._serialized_start=113
  _globals['_PRODUCTSERVICE']._serialized_end=179
# @@protoc_insertion_point(module_scope)
